//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyAndSecurityForNSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public System.Guid ApplicationId { get; set; }
        public int BirthId { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string ApplicationType { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public int NID { get; set; }
    }
}
