//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyAndSecurityForNSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriminalRecordEntry
    {
        public System.Guid CrimeId { get; set; }
        public string Name { get; set; }
        public Nullable<long> Nid { get; set; }
        public Nullable<long> BirthId { get; set; }
        public Nullable<long> SSN { get; set; }
        public Nullable<long> ParentsNid { get; set; }
        public string PassportNo { get; set; }
        public string CrimeType { get; set; }
        public string CrimeDetails { get; set; }
        public string Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
