//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyAndSecurityForNSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsEntryModel
    {
        public System.Guid DoctorsId { get; set; }
        public string DoctorName { get; set; }
        public string DegreeOne { get; set; }
        public string DegreeTwo { get; set; }
        public string DegreeThree { get; set; }
        public string TrainingInstitute { get; set; }
        public string TrainingPeriod { get; set; }
        public string SpecialTraining { get; set; }
        public string BMAMembershipNo { get; set; }
        public string BranceCode { get; set; }
        public string MembershipCategory { get; set; }
        public string BcsRegNo { get; set; }
        public int NID { get; set; }
        public string DoctorImage { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
