//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyAndSecurityForNSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovernmentJob
    {
        public System.Guid JobId { get; set; }
        public string DepartmentName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Body { get; set; }
        public string JobTitle { get; set; }
    }
}
