//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyAndSecurityForNSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceClearanceModel
    {
        public System.Guid ThanaId { get; set; }
        public string ThanaName { get; set; }
        public string TokenNumber { get; set; }
        public string ThanaDetails { get; set; }
        public string OfficerName { get; set; }
        public long NID { get; set; }
        public string PassportNo { get; set; }
        public string PoliceClearImg { get; set; }
        public string Gender { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
