//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyAndSecurityForNSI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSFORNSIDBFinalEntities : DbContext
    {
        public SSFORNSIDBFinalEntities()
            : base("name=SSFORNSIDBFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationCategory> ApplicationCategories { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<CarLoanModel> CarLoanModels { get; set; }
        public virtual DbSet<CitizenShipModel> CitizenShipModels { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DMemberShipCategoryModel> DMemberShipCategoryModels { get; set; }
        public virtual DbSet<DoctorsEntryModel> DoctorsEntryModels { get; set; }
        public virtual DbSet<EthnicityModel> EthnicityModels { get; set; }
        public virtual DbSet<ForeignCitizenModel> ForeignCitizenModels { get; set; }
        public virtual DbSet<HomeLoanModel> HomeLoanModels { get; set; }
        public virtual DbSet<LocalCitizenModel> LocalCitizenModels { get; set; }
        public virtual DbSet<PoliceClearanceModel> PoliceClearanceModels { get; set; }
        public virtual DbSet<RaceModel> RaceModels { get; set; }
        public virtual DbSet<SexModel> SexModels { get; set; }
        public virtual DbSet<SSIModel> SSIModels { get; set; }
        public virtual DbSet<TaxEntryModel> TaxEntryModels { get; set; }
        public virtual DbSet<TaxYearModel> TaxYearModels { get; set; }
    }
}
