//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyAndSecurityForNSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxYearModel
    {
        public int TaxYearId { get; set; }
        public long SocialSecurityNumber { get; set; }
        public Nullable<long> NID { get; set; }
        public Nullable<long> ITIN { get; set; }
        public string EIN { get; set; }
    }
}
